# Generated by Django 4.2.1 on 2023-06-28 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dt_end',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 15, 8, 15, 332641)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='dt_start',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 15, 8, 17, 957052)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='vacancy_days',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='dt_birth',
            field=models.DateField(),
        ),
    ]
